### PR TITLE
Change name to Aerospike EE Managed Service. Update to version 1.0.0

### PR DESCRIPTION
**Pull request by jboone100**

### CODE REVIEW

**Comment by jncd** [comment]
@jboone100 Thanks for the PR. I'll edit and push.
btw, does the tile on the Marketplace still appear as "Aerospike Enterprise Edition"? (I was looking at the Using topic.

**Comment by CanvasPaints** [comment]
Thanks @jncd. Yes, the product still appears as "Aerospike Enterprise Edition" in the marketplace. We are renaming it to "Aerospike EE Managed Service" for this release.

**Comment by jboone100** [comment]
Sorry. Was signed in on the wrong account.

**Comment by jncd** [comment]
@jboone100 No worries Jeff (aka CanvasPaints).
Maybe put in a PR to change the name of the tile on the Marketplace (line 22 [here](https://github.com/pivotal-cf/docs-aerospike-ee/blob/master/docs-content/using.html.md.erb), when the release is out)

**Pull request merged**
